### ISSUE TITLE
Replace the logger with loguru.

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/tyrant#14]
https://loguru.readthedocs.io/ is a wonderful logger, looks much better than the standard library one.

**Comment by ChrisLovering** [comment]
I've just picked this up, do you want logs to be saved to a log file? If so, what sort of retention/rotation would you like? Here are some examples from their docs

```
logger.add("file_1.log", rotation="500 MB")    # Automatically rotate too big file
logger.add("file_2.log", rotation="12:00")     # New file is created each day at noon
logger.add("file_3.log", rotation="1 week")    # Once the file is too old, it's rotated

logger.add("file_X.log", retention="10 days")  # Cleanup after some time
```

**Comment by onerandomusername** [comment]
#17 should have closed this, @lemonsaurus
